Feature/reviews
MagdalenaKusmierczak/m-powered-ice-cream pull request #40
Opened 2022-12-16 23:05 UTC by MarikaGK

Nie działa cudzysłów

2022-12-17 10:19 UTC, MarcinBolt requested changes
Marika, dodaj position: relative; do klasy .customer-reviews__text i będziesz mieć ikonkę schowaną za tekstem komentarza :)

2022-12-17 10:19 UTC, MarcinBolt commented on src/sass/partials/_customer-reviews.scss
>    text-align: center;
Marika, dodaj **_position: relative;_** do klasy _.customer-reviews__text_ i będziesz mieć ikonkę schowaną za tekstem komentarza :)

2022-12-17 12:03 UTC, MarcinBolt requested changes
Klasa _customer-reviews__review_ dla mobile powinna mieć poprawione paddingi - odstęp; gówny i dolny powiny być jeszcze raz przeliczone, a lewy został zamieniony z prawym, a margin można wyrzucić dostosowując padding dolny tak, aby nie usunąć ostatniego gradientu. Nie sprawdzałem już dla tabletu i desktopa. Jeśli możesz to zerknij na nie :)

Ikona Quotation-icon powinna mieć nieco inne przesunięcia: w relacji do tekstu komentarza.

Slider ma niezerowe marginesy górny i dolny. Powinnaś je wyzerować.

2022-12-17 12:03 UTC, MarcinBolt commented on src/sass/partials/_customer-reviews.scss
>    padding: 6px 7px 0 16px;
Padding w mobile jest zamieniony lewy z prawym. Ponownie nalezy przeliczyć padding górny i dolny. Można wtedy pozbyć się dolnego marginesu.

2022-12-17 12:03 UTC, MarcinBolt commented on src/sass/partials/_customer-reviews.scss
>    letter-spacing: 0.04em;
Nie zauważyłem w figmie zdefiniowania odstępów między literami.

2022-12-17 12:09 UTC, MarikaGK commented
gotowe

2022-12-17 12:46 UTC, MarcinBolt requested changes
Ikona powinna być w relacji do tekstu przesunięta top: 15px; i left: 4px;
Zwiększyć paddingi dla customer-reviews__review; górny licząc od cudzysłowu powinien mieć 28px; Trzeba też zwiększyć dolny odstęp tekstu do ikony 3-kropek.
Wyzeruj margines górny i dolny dla customer-reviews__text. Bo to chyba dla tagu p z automatu dodaje.

2022-12-17 13:14 UTC, MagdalenaKusmierczak commented
Do aktualizacji plik main scss z dev

2022-12-17 20:25 UTC, MarcinBolt requested changes
Wszystko prawie super, tylko odstępy między kolejnymi elementami (komentarz i ikona 3-kropek) w pionie się zwiększyły poprzez połączenie wartości margin + padding,, przez co są za daleko siebie - względem projektu w figmy.

2022-12-18 13:47 UTC, MarcinBolt approved these changes
After one little value correction - Pixel-perfect! 
GREAT JOB MARIKA !!!

2022-12-18 13:47 UTC, MarcinBolt commented on src/sass/partials/_customer-reviews.scss
> +  padding: 80px 86px 174px;
Correct value of padding-bottom is 170px.
I'll change it for You Marika.

2022-12-18 14:52 UTC, merged